### ISSUE TITLE
Should be simplified with default GUID format

### ISSUE THREAD

**Issue by MarkBrainfire** [paiden/GuidFac#1]
Inserting a GUID should be as simple as possible.  Allow the user to select a default GUID format so that Ctrl E, G just inserts this without a popup menu, selection and additional return required.

**Comment by paiden** [comment]
The extension is attuned to my use case and works well enough for that:

- Rarely need a GUID
- But need them in a specific format because using various (and sometimes old) tech stacks

Because of that I do not intend to invest time to change the extension behavior.

I think for your use case some other extension like: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.insertguid may be better suited.
